window.ITALY_GUIDE_V010 = {
  "area": {
    "id": "A01",
    "name_zh": "罗马及意大利中部",
    "name_en": "Rome & Central Italy",
    "name_it": "Roma e Italia centrale",
    "description_zh": "以罗马为主要旅行枢纽，并连接白露里治奥与奥尔维耶托。",
    "description_en": "Rome as the main hub, with Civita di Bagnoregio and Orvieto as linked destinations."
  },
  "destinations": [
    {
      "id": "D000",
      "area_id": "A01",
      "parent_id": null,
      "name_zh": "罗马及意大利中部",
      "name_en": "Rome & Central Italy",
      "name_it": "Roma e Italia centrale",
      "type": "area",
      "popularity": null,
      "recommended_days": null,
      "notes_zh": null,
      "source_page": null,
      "map_show": false
    },
    {
      "id": "D001",
      "area_id": "A01",
      "parent_id": "D000",
      "name_zh": "罗马",
      "name_en": "Rome",
      "name_it": "Roma",
      "type": "city",
      "popularity": 5.0,
      "recommended_days": "3-4",
      "notes_zh": null,
      "source_page": 23,
      "map_show": true
    },
    {
      "id": "D002",
      "area_id": "A01",
      "parent_id": "D001",
      "name_zh": "梵蒂冈",
      "name_en": "Vatican City",
      "name_it": "Città del Vaticano",
      "type": "area",
      "popularity": null,
      "recommended_days": null,
      "notes_zh": "在原攻略中作为罗马内部的观光子区域。",
      "source_page": 23,
      "map_show": true
    },
    {
      "id": "D003",
      "area_id": "A01",
      "parent_id": "D001",
      "name_zh": "白露里治奥",
      "name_en": "Civita di Bagnoregio",
      "name_it": "Civita di Bagnoregio",
      "type": "town",
      "popularity": 2.0,
      "recommended_days": "0.5",
      "notes_zh": null,
      "source_page": 184,
      "map_show": true
    },
    {
      "id": "D004",
      "area_id": "A01",
      "parent_id": "D001",
      "name_zh": "奥尔维耶托",
      "name_en": "Orvieto",
      "name_it": "Orvieto",
      "type": "town",
      "popularity": 2.0,
      "recommended_days": "0.5",
      "notes_zh": null,
      "source_page": 186,
      "map_show": true
    }
  ],
  "places": [
    {"id":"P0001","area_id":"A01","destination_id":"D002","map_type":"attraction","name_zh":"梵蒂冈博物馆","name_en":"Vatican Museums","name_it":"Musei Vaticani","subtype":"museum_gallery","tags_zh":["博物馆","美术馆","艺术"],"address":"00120 Vatican City","official_url":"https://tickets.museivaticani.va/home","map_show":true,"opening_hours_en":"Mon–Sat 08:00–20:00; final entry 18:00. Last Sunday of the month 09:00–14:00; final entry 12:30.","source_page":23,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0002","area_id":"A01","destination_id":"D002","map_type":"attraction","name_zh":"圣彼得大教堂","name_en":"St. Peter's Basilica","name_it":"Basilica di San Pietro","subtype":"church_religious","tags_zh":["教堂","大教堂","宗教"],"address":"Piazza San Pietro, 00120 Città del Vaticano, Vatican City","official_url":"https://www.basilicasanpietro.va/it/","map_show":true,"opening_hours_en":null,"source_page":24,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0003","area_id":"A01","destination_id":"D001","map_type":"attraction","name_zh":"圣天使堡","name_en":"Castel Sant'Angelo","name_it":"Castel Sant'Angelo","subtype":"castle_palace","tags_zh":["城堡","宫殿","历史建筑"],"address":"Lungotevere Castello, 50, 00193 Roma RM, Italy","official_url":null,"map_show":true,"opening_hours_en":null,"source_page":25,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0004","area_id":"A01","destination_id":"D001","map_type":"attraction","name_zh":"纳沃纳广场","name_en":"Piazza Navona","name_it":"Piazza Navona","subtype":"square","tags_zh":["广场","公共空间"],"address":"Piazza Navona, 00186 Roma RM, Italy","official_url":null,"map_show":true,"opening_hours_en":"Open 24 hours.","source_page":25,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0005","area_id":"A01","destination_id":"D001","map_type":"attraction","name_zh":"万神殿","name_en":"Pantheon","name_it":"Pantheon","subtype":"landmark","tags_zh":["景点","地标"],"address":"Piazza della Rotonda, 00186 Roma RM, Italy","official_url":null,"map_show":true,"opening_hours_en":null,"source_page":26,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0006","area_id":"A01","destination_id":"D001","map_type":"attraction","name_zh":"圣安德烈圣殿","name_en":"Basilica of Sant'Andrea della Valle","name_it":"Basilica di Sant'Andrea della Valle","subtype":"church_religious","tags_zh":["教堂","大教堂","宗教"],"address":null,"official_url":"https://santandrea.teatinos.org/","map_show":true,"opening_hours_en":null,"source_page":28,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0007","area_id":"A01","destination_id":"D001","map_type":"attraction","name_zh":"特莱维喷泉（许愿池）","name_en":"Trevi Fountain","name_it":"Fontana di Trevi","subtype":"fountain","tags_zh":["喷泉","地标"],"address":"Piazza di Trevi, 00187 Roma RM, Italy","official_url":null,"map_show":true,"opening_hours_en":null,"source_page":28,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0008","area_id":"A01","destination_id":"D001","map_type":"attraction","name_zh":"圣母大殿","name_en":"Papal Basilica of Saint Mary Major","name_it":"Basilica Papale di Santa Maria Maggiore","subtype":"church_religious","tags_zh":["教堂","大教堂","宗教"],"address":"P.za di Santa Maria Maggiore, 00100 Roma RM, Italy","official_url":null,"map_show":true,"opening_hours_en":null,"source_page":30,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0009","area_id":"A01","destination_id":"D001","map_type":"attraction","name_zh":"斗兽场","name_en":"Colosseum","name_it":"Colosseo","subtype":"archaeological_site","tags_zh":["考古","遗址","古迹","古代历史"],"address":"P.za del Colosseo, 1, 00184 Roma RM, Italy","official_url":null,"map_show":true,"opening_hours_en":null,"source_page":32,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0010","area_id":"A01","destination_id":"D001","map_type":"attraction","name_zh":"美第奇别墅","name_en":"Villa Medici","name_it":"Villa Medici","subtype":"landmark","tags_zh":["景点","地标"],"address":"Viale della Trinità dei Monti, 1, 00187 Roma RM, Italy","official_url":null,"map_show":true,"opening_hours_en":null,"source_page":34,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0011","area_id":"A01","destination_id":"D001","map_type":"attraction","name_zh":"西班牙广场与西班牙台阶","name_en":"Spanish Steps","name_it":"Piazza di Spagna","subtype":"square","tags_zh":["广场","公共空间"],"address":"00187 Rome, Metropolitan City of Rome Capital, Italy","official_url":null,"map_show":true,"opening_hours_en":null,"source_page":35,"review_status":"review","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0012","area_id":"A01","destination_id":"D001","map_type":"attraction","name_zh":"博尔盖塞美术馆","name_en":"Borghese Gallery","name_it":"Galleria Borghese","subtype":"museum_gallery","tags_zh":["博物馆","美术馆","艺术"],"address":"Piazzale Scipione Borghese, 5, 00197 Roma RM, Italy","official_url":null,"map_show":true,"opening_hours_en":"Tue–Sun 09:00–19:00; closed Monday.","source_page":37,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0013","area_id":"A01","destination_id":"D001","map_type":"attraction","name_zh":"古罗马广场","name_en":"Roman Forum","name_it":"Foro Romano","subtype":"archaeological_site","tags_zh":["考古","遗址","古迹","古代历史"],"address":"00186 Rome, Metropolitan City of Rome Capital, Italy","official_url":null,"map_show":true,"opening_hours_en":null,"source_page":39,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0014","area_id":"A01","destination_id":"D001","map_type":"attraction","name_zh":"真理之口","name_en":"Mouth of Truth","name_it":"Bocca della Verità","subtype":"landmark","tags_zh":["景点","地标"],"address":null,"official_url":null,"map_show":true,"opening_hours_en":null,"source_page":41,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0015","area_id":"A01","destination_id":"D001","map_type":"attraction","name_zh":"马耳他骑士团钥匙孔","name_en":"Keyhole of the Order of Malta","name_it":"Buco della Serratura dell'Ordine di Malta","subtype":"landmark","tags_zh":["景点","地标"],"address":"Piazza dei Cavalieri di Malta, 4, 00153 Roma RM, Italy","official_url":null,"map_show":true,"opening_hours_en":null,"source_page":41,"review_status":"review","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0016","area_id":"A01","destination_id":"D001","map_type":"attraction","name_zh":"多利亚·潘菲利别墅公园","name_en":"Villa Doria Pamphilj Park","name_it":"Villa Doria Pamphilj","subtype":"park_garden","tags_zh":["公园","花园","绿地"],"address":"Via di San Pancrazio, 00152 Roma RM, Italy","official_url":null,"map_show":true,"opening_hours_en":null,"source_page":41,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0017","area_id":"A01","destination_id":"D001","map_type":"attraction","name_zh":"贾尼科洛山","name_en":"Janiculum Hill","name_it":"Gianicolo","subtype":"trail_nature","tags_zh":["徒步","步道","自然","户外"],"address":"Municipio I, 00165 Roma RM, Italy","official_url":null,"map_show":true,"opening_hours_en":"Open 24 hours; evening visits are suitable for sunset views.","source_page":42,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0018","area_id":"A01","destination_id":"D001","map_type":"attraction","name_zh":"特拉斯提弗列","name_en":"Trastevere","name_it":"Trastevere","subtype":"landmark","tags_zh":["景点","地标"],"address":null,"official_url":null,"map_show":true,"opening_hours_en":null,"source_page":42,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0019","area_id":"A01","destination_id":"D001","map_type":"food","name_zh":"特斯塔乔市场","name_en":"Testaccio Market","name_it":"Mercato Testaccio","subtype":"market_shopping","tags_zh":["市场","购物","美食市场","当地美食"],"address":"Via Aldo Manuzio, 66b, 00153 Roma RM, Italy","official_url":"http://www.mercatoditestaccio.it/","map_show":true,"opening_hours_en":null,"source_page":43,"review_status":"review","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0020","area_id":"A01","destination_id":"D001","map_type":"experience","name_zh":"罗马冰吧","name_en":"Ice Club Roma","name_it":"Ice Club Roma","subtype":"landmark","tags_zh":["景点","地标","夜生活","主题酒吧","体验"],"address":"Via della Madonna dei Monti, 18/19, 00184 Roma RM, Italy","official_url":null,"map_show":true,"opening_hours_en":null,"source_page":44,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0021","area_id":"A01","destination_id":"D001","map_type":"food","name_zh":"缪斯酒吧","name_en":"Il Bar della Musa","name_it":"Il Bar della Musa","subtype":"bar_food","tags_zh":["酒吧","餐饮","饮品","夜生活","鸡尾酒"],"address":"Largo del Nazareno, 25, 00187 Roma RM, Italy","official_url":null,"map_show":true,"opening_hours_en":null,"source_page":44,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0022","area_id":"A01","destination_id":"D001","map_type":"food","name_zh":"当地美食推荐","name_en":"Local Food Recommendations","name_it":"Specialità locali consigliate","subtype":"landmark","tags_zh":["当地美食","菜系","美食指南"],"address":null,"official_url":null,"map_show":false,"opening_hours_en":null,"source_page":44,"review_status":"review","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0108","area_id":"A01","destination_id":"D003","map_type":"attraction","name_zh":"圣多纳托教堂","name_en":"Church of San Donato","name_it":"Chiesa di San Donato","subtype":"church_religious","tags_zh":["教堂","大教堂","宗教"],"address":"Piazza del Vescovado, 11, 01022 Civita VT, Italy","official_url":null,"map_show":true,"opening_hours_en":null,"source_page":184,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0109","area_id":"A01","destination_id":"D003","map_type":"attraction","name_zh":"圣多纳托广场","name_en":"Piazza San Donato","name_it":"Piazza San Donato","subtype":"square","tags_zh":["广场","公共空间"],"address":"01022 Civita di Bagnoregio, VT, Italy","official_url":null,"map_show":true,"opening_hours_en":null,"source_page":185,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0110","area_id":"A01","destination_id":"D004","map_type":"attraction","name_zh":"圣帕特里克井","name_en":"St. Patrick's Well","name_it":"Pozzo di San Patrizio","subtype":"landmark","tags_zh":["景点","地标"],"address":"Piazza Cahen, 5B, 05018 Orvieto TR, Italy","official_url":"https://liveorvieto.com/blog/monumenti/pozzo-di-san-patrizio/","map_show":true,"opening_hours_en":null,"source_page":186,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0111","area_id":"A01","destination_id":"D004","map_type":"attraction","name_zh":"奥尔维耶托主教座堂","name_en":"Orvieto Cathedral","name_it":"Duomo di Orvieto","subtype":"church_religious","tags_zh":["教堂","大教堂","宗教"],"address":"Piazza del Duomo, 26, 05018 Orvieto TR, Italy","official_url":"https://www.duomodiorvieto.it/","map_show":true,"opening_hours_en":null,"source_page":188,"review_status":"ready","preview_image":null,"image_status":"illustration_placeholder"},
    {"id":"P0112","area_id":"A01","destination_id":"D004","map_type":"attraction","name_zh":"奥尔维耶托地下城","name_en":"Orvieto Underground","name_it":"Orvieto Underground","subtype":"landmark","tags_zh":["景点","地标"],"address":"Piazza del Duomo, 23, 05018 Orvieto TR, Italy","official_url":"http://www.orvietounderground.it/","map_show":true,"opening_hours_en":null,"source_page":188,"review_status":"review","preview_image":null,"image_status":"illustration_placeholder"}
  ]
};
